sirin yarar (week 3 homework edited and done)
HackYourHomework/Homework-class37 pull request #11
Opened 2022-04-12 17:23 UTC by sirinyarar

2022-04-13 08:55 UTC, robvk commented
You seem to have commited a .history folder as well. For this PR we can look past it but for next one try to figure out how to only commit your changes

2022-04-14 11:24 UTC, bnhoogendijk requested changes
Hi Sirin, I am afraid something went wrong when you committed and pushed your changes. I don't see your code. Only indentation changes. Could you try and commit your solutions again? You can check in GitHub if things are ok, if you click on your PR and then go to the `files changed` tab. you should see your code there. Find me on slack if you need help here.

2022-04-15 23:32 UTC, sirinyarar commented
> Hi Sirin, I am afraid something went wrong when you committed and pushed your changes. I don't see your code. Only indentation changes. Could you try and commit your solutions again? You can check in GitHub if things are ok, if you click on your PR and then go to the `files changed` tab. you should see your code there. Find me on slack if you need help here.

Hi Bas, I fixed it. could you check it again please?  Thanks in Advance!

2022-04-18 19:55 UTC, bnhoogendijk approved these changes
Your coding is very good, Sirin! You clearly demonstrate that you master the javascript concepts of this week! Keep going like this! See if you can figure out the git part, for next week. Or ask some help during the next class.

2022-04-18 19:55 UTC, bnhoogendijk commented on .history/1-JavaScript/Week3/homework/ex1-giveCompliment_20220416004313.js
> +    const compliment = compliments[Math.floor(Math.random() * compliments.length)];
Excellent!

2022-04-18 19:55 UTC, bnhoogendijk commented on .history/1-JavaScript/Week3/homework/ex2-dogYears_20220416004352.js
> +    return `Your doggie is ${age} years old in dog years!`;
Well done 👏

2022-04-18 19:55 UTC, bnhoogendijk commented on .history/1-JavaScript/Week3/homework/ex3-tellFortune_20220416005015.js
> +    return items[Math.floor(Math.random() * items.length)];
Great how you used the length of the items array to calculate the random value!

2022-04-18 19:55 UTC, bnhoogendijk commented on .history/1-JavaScript/Week3/homework/ex5-shoppingCartPure_20220416005634.js
> +    }
Great job! Did you now you can also provide a negative integer to the `.slice` function? The effect is that it counts  the slice start from the end of the array.

2022-04-18 19:55 UTC, bnhoogendijk commented on .history/1-JavaScript/Week3/homework/ex6-totalCost_20220416010139.js
> +        for (let items in shoppingCart) {
if you loop over items of an array or keys/ values of an object it might be easier to give the variable a singular name. So instead of `items` use `item`. I know it is a minor comment, because overall you made it work, and that's what counts :-)

2022-04-18 19:55 UTC, bnhoogendijk commented on .history/1-JavaScript/Week3/homework/ex7-mindPrivacy_20220416010855.js
> +            return { name, occupation, email };
Great solution 👏 Just for the fun consider the following:
```javascript
employeeRecordsArr.map(({name, occupation, email}) => ({name, occupation, email}))
```
It does the same and you could even return it directly. Keep in mind; it is not better, only differently written. You can decide for yourself which style you like better off course 🙂

2022-04-19 12:57 UTC, sirinyarar commented on .history/1-JavaScript/Week3/homework/ex6-totalCost_20220416010139.js
> +        for (let items in shoppingCart) {
Thank you @bnhoogendijk  I really appreciate your effort in giving feedback.

> Your coding is very good, Sirin! You clearly demonstrate that you master the javascript concepts of this week! Keep going like this! See if you can figure out the git part, for next week. Or ask some help during the next class.

Thank you @bnhoogendijk  I really appreciate your effort in giving feedback.

2022-04-19 12:59 UTC, sirinyarar commented on .history/1-JavaScript/Week3/homework/ex7-mindPrivacy_20220416010855.js
> +            return { name, occupation, email };
Thank you 🙂

2022-05-04 08:16 UTC, closed without merging